SET BANN=Banner
SET BCKD=Backdrop
SET CONS=Console
SET CXML=ConsoleXML
SET ECFG=EmuCfg
SET EMUZ=Emulators
SET EMEX=EmuEx
SET FLDR=Folder
SET FNRT=Fanart
SET GAM=Games
SET LNCH=Launchers
SET PLGN=plugins
SET RAR=rar
set EXECT=Executables
SET BTEXE=Bat_To_Exe_Converter.exe
SET ROMJ=RoM-Jacket
SET VCRD=vcrs
SET VIDE=Videos
SET XPROF=Xprofiles
SET XCONF=XpadCFG

SET ADVL=Advanced Launcher
SET CABR=cabrio
SET DAEMNT=Daemon Tools
SET DXWS=dxwebsetup
SET GAMEX=GameEx
SET GBRWS=GameBrowser
SET HYPS=Hyperspin
SET OBLYT=Oblytile
SET JOY2K=Joy2Key
SET J2KPROF=J2KProfiles
SET MBRWS=MediaBrowser
SET OPNAL=OPENAL
SET PS3JOY=PS3Driver
SET RCBRWS=Rom Collection Browser
SET XBCE=x360ce
SET XBJOY=XBoxDriver
SET XBMC=XBMC
SET XPADR=Xpadder

SET ACAN=Funtech Super A'can
SET ACBBC=Acorn BBC
SET ACARC=Acorn Archimedes
SET ACELE=Acorn Electron
SET ADVV=Adventure Vision
SET AMSTR=Amstrad CPC
SET ALG=American Laser Games
SET AMIG32=Commodore Amiga CD32
SET APL2E=Apple IIe
SET APL2GS=Apple IIgs
SET ARCD=Arcade
SET AT26=Atari 2600
SET AT52=Atari 5200
SET AT78=Atari 7800
SET AT8H=Atari 800
SET ATST=Atari ST
SET ATMS=Atomiswave
SET BALY=Bally Astrocade
SET BWS=Bandai Wonder Swan
SET BWSC=Bandai Wonder Swan Color
SET CAMIG=Commodore Amiga
SET CDI=Philips CD-I
SET CHNF=Fairchild Channel F
SET CM64=Commodore 64
SET COLEC=ColecoVision
SET CPS=CPS
SET CPS2=CPS 2
SET CPS3=CPS 3
SET EMARC=Arcadia 2001
SET ENTP=Enterprise 64
SET EXPSXE=ePSXe
SET DAPHN=Daphne
SET FLASH=Flash Games
SET FM7=FM-7
SET FMTOWNS=FM Towns
SET INTEL=Intellivision
SET IMAG=Imagination Machine
SET JAGCD=Atari Jaguar CD
SET JAG=Atari Jaguar
SET LYNX=Atari Lynx
SET MDUC=Mega Duck
SET MSDS=MS D-O-S
SET MTX=MTX
SET MSX=MSX
SET N64=Nintendo 64
SET NAOMI=Naomi
SET NEOPKT=NeoGeo Pocket
SET NEOPKTC=NeoGeo Pocket Color
SET NEOGE=NeoGeo MVS
SET NEOCD=NeoGeo CD
SET NEO64=Hyper NeoGeo 64
SET NDS=Nintendo DS
SET NVB=Nintendo Virtual Boy
SET NGC=Nintendo GameCube
SET NGB=Nintendo Gameboy
SET NGBC=Nintendo Gameboy Color
SET NGBA=Nintendo Gameboy Advance
SET NES=Nintendo Entertainment System
SET NFAM=Nintendo Famicom
SET ODYS=Odessey
SET P3DO=Panasonic 3DO
SET PC88=NEC PC88
SET PC98=NEC PC98
SET PCAP=PopCap
SET PCECD=PC Engine CD
SET PCENG=PC Engine
SET PCFX=NEC PC-FX
SET PS1=Sony Playstation
SET PS2=Sony Playstation 2
SET PS3=Sony PS3
SET PSP=Sony PSP
SET OBOR=Beats of Rage
SET ORIC=Tangerine Oric
SET PV1K=Casio PV-1000
SET SAMC=Sam Coupe
SET SCUM=ScummVM
SET SCAS=Super Cassette Vision
SET SEG1K=Sega SG-1000
SET SEGAG=Sega Genesis
SET SEGAMD=Sega MegaDrive
SET SEGMS=Sega Master System
SET SEGDC=Sega Dreamcast
SET SEGG=Sega Game Gear
SET SEGCD=Sega CD
SET SEGM2=Sega Model 2
SET SEGM3=Sega Model 3
SET SFAM=Super Famicom
SET SG32X=Sega 32X
SET SGFX=SuperGrafx
SET SNES=Super Nintendo
SET SPCO=Sega PICO
SET SSAT=Sega Saturn
SET SSTV=Sega STV
SET SHRPX1=Sharp X1
SET SVIS=SuperVision
SET TAITX=Taito Type X
SET TG16=TurboGrafx 16
SET TGCD=TurboGrafx CD
SET TOUHU=Touhou
SET TRIF=Triforce
SET VECTX=Vectrex
SET VC4K=Interon VC 4000
SET VC20=Commodore VIC20
SET VCRV=VTech Creativision
SET X360=Xbox 360
SET X68K=X68000
SET XBX=Xbox
SET WII=Nintendo Wii
SET WIN32=Windows Games
SET ZXSP=Sinclair ZX Spectrum

SET A800=Atari800
SET AKIKO=Akiko
SET ALTRA=Altirra
SET ARCEM=ArcEm
SET ARLTR=Arculator
SET ANEX=Anex86
SET APCL=ArcadePCLoader
SET APLWIN=AppleWin
SET ATRI=atari++
SET BATCHL=BatchScriptLauncher
SET BEEBEM=BeebEm
SET BSNS=bsnes
SET BMSX=BlueMSX
SET CPS3EMU=cps3emulator
SET COLEM=Colem
SET DMUL=Demul
SET DESMUME=DesMume
SET DOLPH=Dolphin
SET ELECEM=ElectrEm
SET EMSEV=em7
SET EPSXE=ePSXe
SET FBA=FinalBurnAlpha
SET FMUNZ=Unz
SET FOURDO=4DO
SET FSHPL=FlashPlayer
SET FRDO=FreeDO
SET FSUAE=FS-UAE
SET FUSN=Fusion
SET FCEUX=fceux
SET HATARI=hatari
SET INTV=Bliss
SET JUM52=jum52
SET JAGLT=Jagulator
SET JNES=jnes
SET JPCSP=jpcsp
SET JZINTV=jzintv
SET KEGS=Kegs32
SET M88=M88
SET M2EMU=m2emulator
SET MEDN=Mednafen
SET MENG=MagicEngine
SET MAME=Mame
SET MESS=Mess
SET MSBOX=DOSBox
SET MUGN=Mugen
SET NEBULA=Nebula
SET NEKO=Neko
SET NEOCDEMU=neocd
SET NEORAINE=NeoRaine
SET NESTP=nestopia
SET NOGBA=No$GBA
SET NOSTL=Nostalgia
SET NULLDC=NullDC
SET OOTK=Ootake
SET OPNMSX=OpenMSX
SET PCSX2=Pcsx2
SET PCAP=Pop Cap
SET PJ64=Project64
SET PJVE=ParaJVE
SET PLAY3DO=3DOplay
SET PROSYS=ProSystem
SET PSSP=PPSSPP
SET PSX=psx
SET PTMPS=ProjectTempest
SET RAINE=Raine
SET SCMVM=ScummVM
SET SIMC=SimCoupe
SET SNES9X=snes9x
SET SNESGT=SNESGT
SET SPRM3=Supermodel
SET SSF=SSF
SET STEEM=Steem
SET STLA=Stella
SET SWFPL=FlashPlayer
SET TURBOE=TurboEngine
SET VCOLEC=VirtualColeco
SET VGBA=VisualBoyAdvance
SET VICE=WinVICE
SET VJAG=VirtualJaguar
SET VNES=VirtuaNes
SET VSVH=EMU7800
SET WCDI=CD-I
SET WINARC=WinArcadia
SET WINAPE=WinAPE
SET WINUAE=WinUAE
SET WINX68K=WinX68k
SET XM6=XM6
SET XM7=XM7
SET XTURB=X1turbo
SET ZINC=Zinc
SET ZSNS=Zsnes
SET ZXSPIN=ZXSpin