%GBD%
cd "%GBC%"
SET GGOFF=
SET GGON=
CALL "%GBC%\delRomJCfg.bat"
"%SEVENZIP%" x -y "%GBC%\net\%LNCH%\%LNCH%.zip" -o"%GBC%\net\%LNCH%"

:CFGtst
if "%XFG%"=="1" goto :GGON
if "%XFG%"=="0" goto :GGOFF

:CFGOPTION
"%GBC%\wbox.exe" "pergame" "^Would you like to enable^''per-game''^configurations for all consoles?" "Yes;No" /DB=1
if %ERRORLEVEL%==1 goto :GGON
if %ERRORLEVEL%==2 goto :GGOFF
goto :INDVOUT
cmd /c start "" "%GBC%\Wbusy.exe" "Preparing Launchers" "Preparing Launchers"  /marquee
:GGON
SET XFG=1
SET GGON=1
CALL "%GBC%\setLocSet.bat"
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" [XFG] --remove
goto :MMontst
:GGOFF
SET XFG=0
SET GGOFF=1
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" "[XFG]" "REM [XFG]"
goto :MMontst

:MMontst
if "%GBM%"=="0" goto :dmonOFF
:dmonON
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" [DSP] --remove
goto :xpdtst
:dmonOFF
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" [DSP] "REM "[DSP]"
:xpdtst
if "%XPADDER%"=="DISABLED" goto :xpdds
if "%XPADDER%"=="[XPD]" goto :xpdds
:xpden
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" --remove [XPT]
goto :dtest
:xpdds
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" "[XPT]" "REM [XPT]"
:dtest
if "%DAMVAR%"=="DISABLED" goto :dten
if "%DAMVAR%"=="[DAM]" goto :dtdel
goto :dten
:dten
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" --remove [DMT]
goto :J2Ktst
:dtdel
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" "[DMT]" "REM [DMT]"
:J2Ktst
if "%XPADDER%" NEQ "DISABLED" goto :setupinjection
if "%JOY2KEY%"=="DISABLED" goto :J2Kds
if "%JOY2KEY%"=="[J2K]" goto :J2Kds
:J2Ken
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" --remove "REM [XPT]"
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" XPADDER JOY2KEY
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" xpadderprofile cfg
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" "^%^CD%%\%%~na2" --remove
goto :setupinjection
:J2Kds
"%GBC%\fart.exe" -r "%GBC%\net\%LNCH%\*.bat" "[XPT]" "REM [XPT]"
goto :setupinjection

:setupinjection
if "%ARPOP%"=="64" set M2ARPOP=emulator_multicpu
if "%ARPOP%"=="32" set M2ARPOP=emulator
pushd "%GBC%\net\%LNCH%"
"%GBC%\fart.exe" "%BWS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%BWS%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%BWS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%BWS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%BWSC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%BWSC%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%BWSC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%BWSC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%CM64%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%VICE%"
"%GBC%\fart.exe" "%CM64%\zz.bat" [EMUZ] "x64"
"%GBC%\fart.exe" "%CM64%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CM64%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SAMC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%SIMC%"
"%GBC%\fart.exe" "%SAMC%\zz.bat" [EMUZ] "%SIMC%"
"%GBC%\fart.exe" "%SAMC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SAMC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%P3DO%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FOURDO%"
"%GBC%\fart.exe" "%P3DO%\zz.bat" [EMUZ] "%FOURDO%"
"%GBC%\fart.exe" "%P3DO%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%P3DO%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AT8H%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ALTRA%"
"%GBC%\fart.exe" "%AT8H%\zz.bat" [EMUZ] "%ALTRA%"
"%GBC%\fart.exe" "%AT8H%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AT8H%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ATST%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%STEEM%"
"%GBC%\fart.exe" "%ATST%\zz.bat" [EMUZ] "%STEEM%z"
"%GBC%\fart.exe" "%ATST%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ATST%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%CDI%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%WCDI%"
"%GBC%\fart.exe" "%CDI%\zz.bat" [EMUZ] "CDIWrapper"
"%GBC%\fart.exe" "%CDI%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CDI%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%FMTOWNS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FMUNZ%"
"%GBC%\fart.exe" "%FMTOWNS%\zz.bat" [EMUZ] "%FMUNZ%"
"%GBC%\fart.exe" "%FMTOWNS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%FMTOWNS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ACARC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ARLTR%"
"%GBC%\fart.exe" "%ACARC%\zz.bat" [EMUZ] "%ARLTR%"
"%GBC%\fart.exe" "%ACARC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ACARC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NEOPKTC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NEOPKTC%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NEOPKTC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NEOPKTC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NEOPKT%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NEOPKT%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NEOPKT%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NEOPKT%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%FLASH%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FSHPL%"
"%GBC%\fart.exe" "%FLASH%\zz.bat" [EMUZ] "FullScreenFlash"
"%GBC%\fart.exe" "%FLASH%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%FLASH%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%N64%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PJ64%"
"%GBC%\fart.exe" "%N64%\zz.bat" [EMUZ] "%PJ64%"
"%GBC%\fart.exe" "%N64%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%N64%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BATCHL%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [EMUZ] "%BATCHL%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PC88%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%M88%"
"%GBC%\fart.exe" "%PC88%\zz.bat" [EMUZ] "%M88%"
"%GBC%\fart.exe" "%PC88%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PC88%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%CAMIG%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FSUAE%"
"%GBC%\fart.exe" "%CAMIG%\zz.bat" [EMUZ] "%FSUAE%"
"%GBC%\fart.exe" "%CAMIG%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CAMIG%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AMIG32%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FSUAE%"
"%GBC%\fart.exe" "%AMIG32%\zz.bat" [EMUZ] "%FSUAE%"
"%GBC%\fart.exe" "%AMIG32%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AMIG32%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SHRPX1%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%XTURB%"
"%GBC%\fart.exe" "%SHRPX1%\zz.bat" [EMUZ] "X1"
"%GBC%\fart.exe" "%SHRPX1%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SHRPX1%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%INTEL%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NOSTL%"
"%GBC%\fart.exe" "%INTEL%\zz.bat" [EMUZ] "%NOSTL%"
"%GBC%\fart.exe" "%INTEL%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%INTEL%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%COLEC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BMSX%"
"%GBC%\fart.exe" "%COLEC%\zz.bat" [EMUZ] "%BMSX%"
"%GBC%\fart.exe" "%COLEC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%COLEC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%APL2GS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%KEGS%"
"%GBC%\fart.exe" "%APL2GS%\zz.bat" [EMUZ] "%KEGS%"
"%GBC%\fart.exe" "%APL2GS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%APL2GS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%APL2E%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%APLWIN%"
"%GBC%\fart.exe" "%APL2E%\zz.bat" [EMUZ] "%APLWIN%"
"%GBC%\fart.exe" "%APL2E%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%APL2E%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AT26%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%STLA%"
"%GBC%\fart.exe" "%AT26%\zz.bat" [EMUZ] "%STLA%"
"%GBC%\fart.exe" "%AT26%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AT26%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AT52%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ATRI%"
"%GBC%\fart.exe" "%AT52%\zz.bat" [EMUZ] "%ATRI%"
"%GBC%\fart.exe" "%AT52%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AT52%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AT78%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PROSYS%"
"%GBC%\fart.exe" "%AT78%\zz.bat" [EMUZ] "%PROSYS%"
"%GBC%\fart.exe" "%AT78%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AT78%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%MSDS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MSBOX%"
"%GBC%\fart.exe" "%MSDS%\zz.bat" [EMUZ] "%MSBOX%"
"%GBC%\fart.exe" "%MSDS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%MSDS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%AMSTR%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%WINAPE%"
"%GBC%\fart.exe" "%AMSTR%\zz.bat" [EMUZ] "%WINAPE%"
"%GBC%\fart.exe" "%AMSTR%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%AMSTR%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%JAGCD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PTMPS%"
"%GBC%\fart.exe" "%JAGCD%\zz.bat" [EMUZ] "PTCDWrapper"
"%GBC%\fart.exe" "%JAGCD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%JAGCD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%JAG%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%VJAG%"
"%GBC%\fart.exe" "%JAG%\zz.bat" [EMUZ] "vjag"
"%GBC%\fart.exe" "%JAG%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%JAG%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%LYNX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%LYNX%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%LYNX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%LYNX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%LYNX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%N64%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%N64%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%N64%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NDS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NOGBA%"
"%GBC%\fart.exe" "%NDS%\zz.bat" [EMUZ] "NDS"
"%GBC%\fart.exe" "%NDS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NDS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%WII%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DOLPH%"
"%GBC%\fart.exe" "%WII%\zz.bat" [EMUZ] "%DOLPH%"
"%GBC%\fart.exe" "%WII%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%WII%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NGC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DOLPH%"
"%GBC%\fart.exe" "%NGC%\zz.bat" [EMUZ] "%DOLPH%"
"%GBC%\fart.exe" "%NGC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NGC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NGB%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NGB%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NGB%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NGB%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NGBC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NGBC%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NGBC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NGBC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NGBA%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%VGBA%"
"%GBC%\fart.exe" "%NGBA%\zz.bat" [EMUZ] "%VGBA%"
"%GBC%\fart.exe" "%NGBA%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NGBA%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NFAM%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NFAM%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NFAM%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NFAM%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NES%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NES%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NES%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NES%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NVB%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%NVB%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%NVB%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NVB%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%TOUHU%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ANEX%"
"%GBC%\fart.exe" "%TOUHU%\zz.bat" [EMUZ] "%ANEX%"
"%GBC%\fart.exe" "%TOUHU%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%TOUHU%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SFAM%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ZSNS%"
"%GBC%\fart.exe" "%SFAM%\zz.bat" [EMUZ] "%ZSNS%w"
"%GBC%\fart.exe" "%SFAM%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SFAM%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SNES%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ZSNS%"
"%GBC%\fart.exe" "%SNES%\zz.bat" [EMUZ] "%ZSNS%w"
"%GBC%\fart.exe" "%SNES%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SNES%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%EMARC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%WINARC%"
"%GBC%\fart.exe" "%EMARC%\zz.bat" [EMUZ] "%WINARC%"
"%GBC%\fart.exe" "%EMARC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%EMARC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%MSX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BMSX%"
"%GBC%\fart.exe" "%MSX%\zz.bat" [EMUZ] "%BMSX%"
"%GBC%\fart.exe" "%MSX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%MSX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NEKO%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [EMUZ] "np21nt"
"%GBC%\fart.exe" "%PC98%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PCFX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%PCFX%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%PCFX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PCFX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%XM6%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [EMUZ] "%XM6%start"
"%GBC%\fart.exe" "%X68K%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEG1K%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEG1K%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEG1K%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEG1K%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGAMD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEGAMD%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEGAMD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGAMD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGAG%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEGAG%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEGAG%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGAG%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGMS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEGMS%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEGMS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGMS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGG%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEGG%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEGG%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGG%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGCD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SEGCD%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SEGCD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGCD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGDC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NULLDC%"
"%GBC%\fart.exe" "%SEGDC%\zz.bat" [EMUZ] "nullDC_Win32_Release-NoTrace"
"%GBC%\fart.exe" "%SEGDC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGDC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SSAT%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%SSF%"
"%GBC%\fart.exe" "%SSAT%\zz.bat" [EMUZ] "%SSF%"
"%GBC%\fart.exe" "%SSAT%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SSAT%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SG32X%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FUSN%"
"%GBC%\fart.exe" "%SG32X%\zz.bat" [EMUZ] "%FUSN%"
"%GBC%\fart.exe" "%SG32X%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SG32X%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PS1%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PSX%"
"%GBC%\fart.exe" "%PS1%\zz.bat" [EMUZ] "%PSX%fin"
"%GBC%\fart.exe" "%PS1%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PS1%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PSP%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%JPCSP%"
"%GBC%\fart.exe" "%PSP%\zz.bat" [EMUZ] "%JPCSP%"
"%GBC%\fart.exe" "%PSP%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PSP%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PS2%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PCSX2%"
"%GBC%\fart.exe" "%PS2%\zz.bat" [EMUZ] "%PCSX2%"
"%GBC%\fart.exe" "%PS2%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PS2%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PCENG%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%PCENG%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%PCENG%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PCENG%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%TG16%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%TG16%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%TG16%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%TG16%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SGFX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%SGFX%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%SGFX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SGFX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%TGCD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%TGCD%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%TGCD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%TGCD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PCECD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MEDN%"
"%GBC%\fart.exe" "%PCECD%\zz.bat" [EMUZ] "%MEDN%"
"%GBC%\fart.exe" "%PCECD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PCECD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BATCHL%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [EMUZ] "%BATCHL%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%WIN32%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%VECTX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%PJVE%"
"%GBC%\fart.exe" "%VECTX%\zz.bat" [EMUZ] "%PJVE%"
"%GBC%\fart.exe" "%VECTX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%VECTX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%FM7%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%XM7%"
"%GBC%\fart.exe" "%FM7%\zz.bat" [EMUZ] "%XM7%"
"%GBC%\fart.exe" "%FM7%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%FM7%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%WINX68K%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [EMUZ] "x68k"
"%GBC%\fart.exe" "%X68K%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%X68K%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NEKO%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [EMUZ] "np21nt"
"%GBC%\fart.exe" "%PC98%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%PC98%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ZXSP%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ZXSPIN%"
"%GBC%\fart.exe" "%ZXSP%\zz.bat" [EMUZ] "%ZXSPIN%"
"%GBC%\fart.exe" "%ZXSP%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ZXSP%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ARCD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MAME%"
"%GBC%\fart.exe" "%ARCD%\zz.bat" [EMUZ] "%MAME%"
"%GBC%\fart.exe" "%ARCD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ARCD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%TAITX%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BATCHL%"
"%GBC%\fart.exe" "%TAITX%\zz.bat" [EMUZ] "%BATCHL%"
"%GBC%\fart.exe" "%TAITX%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%TAITX%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%CPS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FBA%"
"%GBC%\fart.exe" "%CPS%\zz.bat" [EMUZ] "fba"
"%GBC%\fart.exe" "%CPS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CPS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%CPS2%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%MAME%"
"%GBC%\fart.exe" "%CPS2%\zz.bat" [EMUZ] "fba"
"%GBC%\fart.exe" "%CPS2%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CPS2%\zz.bat" [LOC] "%GBG%\%GAM%\%CONS%\%CPS2%"
"%GBC%\fart.exe" "%CPS3%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FBA%"
"%GBC%\fart.exe" "%CPS3%\zz.bat" [EMUZ] "fba"
"%GBC%\fart.exe" "%CPS3%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%CPS3%\zz.bat" [LOC] "%GBG%\%GAM%\%CONS%\%CPS3%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DMUL%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [EMUZ] "%NAOMI%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ATMS%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DMUL%"
"%GBC%\fart.exe" "%ATMS%\zz.bat" [EMUZ] "%ATMS%"
"%GBC%\fart.exe" "%ATMS%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ATMS%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%DAPHN%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DAPHE%"
"%GBC%\fart.exe" "%DAPHN%\zz.bat" [EMUZ] "%DAPHE%"
"%GBC%\fart.exe" "%DAPHN%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%DAPHN%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%DMUL%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [EMUZ] "%NAOMI%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NAOMI%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGM3%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%SPRM3%"
"%GBC%\fart.exe" "%SEGM3%\zz.bat" [EMUZ] "%SPRM3%"
"%GBC%\fart.exe" "%SEGM3%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGM3%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ACELE%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%ELECEM%"
"%GBC%\fart.exe" "%ACELE%\zz.bat" [EMUZ] "Electron"
"%GBC%\fart.exe" "%ACELE%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ACELE%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%ACBBC%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%BEEBEM%"
"%GBC%\fart.exe" "%ACBBC%\zz.bat" [EMUZ] "%BEEBEM%"
"%GBC%\fart.exe" "%ACBBC%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%ACBBC%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%SEGM2%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%M2EMU%"
"%GBC%\fart.exe" "%SEGM2%\zz.bat" [EMUZ] "%M2ARPOP%"
"%GBC%\fart.exe" "%SEGM2%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%SEGM2%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NEOGE%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FBA%"
"%GBC%\fart.exe" "%NEOGE%\zz.bat" [EMUZ] "fba"
"%GBC%\fart.exe" "%NEOGE%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NEOGE%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NEOCD%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%NEORAINE%"
"%GBC%\fart.exe" "%NEOCD%\zz.bat" [EMUZ] "%NEORAINE%32"
"%GBC%\fart.exe" "%NEOCD%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NEOCD%\zz.bat" [XPD] "%XPADDER%"
"%GBC%\fart.exe" "%NEO64%\zz.bat" [EMUL] "%GBE%\%EMUZ%\%FBA%"
"%GBC%\fart.exe" "%NEO64%\zz.bat" [EMUZ] "fba"
"%GBC%\fart.exe" "%NEO64%\zz.bat" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%NEO64%\zz.bat" [XPD] "%XPADDER%"
popd
:injectout
cmd /c start "" "%GBC%\Wbusy.exe" "Preparing Launchers" "Launchers Prepared" /Stop /timeout:1