if /I "%BIOSXT%"=="neogeo.zip" call :BIOSET
if /I "%BIOSXT%"=="neocd.zip" call :BIOSET
if /I "%BIOSXT%"=="cpzn1.zip" call :BIOSET
if /I "%BIOSXT%"=="cpzn2.zip" call :BIOSET
if /I "%BIOSXT%"=="ngdup23a.zip" call :BIOSET
if /I "%BIOSXT%"=="ngdup23c.zip" call :BIOSET
if /I "%BIOSXT%"=="v4bios.zip" call :BIOSET
if /I "%BIOSXT%"=="triforce.zip" call :BIOSET
if /I "%BIOSXT%"=="taitotz.zip" call :BIOSET
if /I "%BIOSXT%"=="sys256.zip" call :BIOSET
if /I "%BIOSXT%"=="sys573.zip" call :BIOSET
if /I "%BIOSXT%"=="sys246.zip" call :BIOSET
if /I "%BIOSXT%"=="stvbios.zip" call :BIOSET
if /I "%BIOSXT%"=="skns.zip" call :BIOSET
if /I "%BIOSXT%"=="shtzone.zip" call :BIOSET
if /I "%BIOSXT%"=="sfcbox.zip" call :BIOSET
if /I "%BIOSXT%"=="sammymdl.zip" call :BIOSET
if /I "%BIOSXT%"=="pyson.zip" call :BIOSET
if /I "%BIOSXT%"=="playch10.zip" call :BIOSET
if /I "%BIOSXT%"=="pgm.zip" call :BIOSET
if /I "%BIOSXT%"=="nss.zip" call :BIOSET
if /I "%BIOSXT%"=="naomi.zip" call :BIOSET
if /I "%BIOSXT%"=="naomi2.zip" call :BIOSET
if /I "%BIOSXT%"=="naomigd.zip" call :BIOSET
if /I "%BIOSXT%"=="megaplay.zip" call :BIOSET
if /I "%BIOSXT%"=="macsbios.zip" call :BIOSET
if /I "%BIOSXT%"=="mac2bios.zip" call :BIOSET
if /I "%BIOSXT%"=="kviper.zip" call :BIOSET
if /I "%BIOSXT%"=="isgsm.zip" call :BIOSET
if /I "%BIOSXT%"=="hod2bios.zip" call :BIOSET
if /I "%BIOSXT%"=="hng64.zip" call :BIOSET
if /I "%BIOSXT%"=="galgbios.zip" call :BIOSET
if /I "%BIOSXT%"=="hikaru.zip" call :BIOSET
if /I "%BIOSXT%"=="f355bios.zip" call :BIOSET
if /I "%BIOSXT%"=="bubsys.zip" call :BIOSET
if /I "%BIOSXT%"=="crysbios.zip" call :BIOSET
if /I "%BIOSXT%"=="chihiro.zip" call :BIOSET
if /I "%BIOSXT%"=="awbios.zip" call :BIOSET
if /I "%BIOSXT%"=="atarisy1.zip" call :BIOSET
if /I "%BIOSXT%"=="ar_bios.zip" call :BIOSET
if /I "%BIOSXT%"=="aleck64.zip" call :BIOSET
if /I "%BIOSXT%"=="alg_bios.zip" call :BIOSET
if /I "%BIOSXT%"=="cr589fw.zip" call :BIOSET
if /I "%BIOSXT%"=="airlbios.zip" call :BIOSET
if /I "%BIOSXT%"=="cr589fwa.zip" call :BIOSET
if /I "%BIOSXT%"=="pgm.zip" call :BIOSET
if /I "%BIOSXT%"=="playch10.zip" call :BIOSET
if /I "%BIOSXT%"=="cvs.zip" call :BIOSET
if /I "%BIOSXT%"=="skns.zip" call :BIOSET
if /I "%BIOSXT%"=="decocass.zip" call :BIOSET