SET FNDEXT=
if /I "%ARCE%"==".ws" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%BWS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wsc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%BWSC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".x64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".t64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".g64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".d64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".xex" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".atr" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".obx" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pro" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NEOPKTC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".neo" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NEOPKTC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngp" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".npk" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".int" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%INTEL%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".col" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%COLEC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a78" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT78%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a26" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT26%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a52" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AT52%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".st" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%ATST%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".msa" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%ATST%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".lnx" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%LYNX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".v64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gb" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NGB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".z64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".n64" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nds" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NDS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nd5" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NDS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gbc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NGBC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".swf" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%FLASH%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".jso" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".cso" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".jag" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%JAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dol" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wad" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wbfs" "%SEVENZIP%" x -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gba" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NGBA%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vb" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NVB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vboy" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NVB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mx2" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%MSX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mx1" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%MSX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".unf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nes" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".smc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SNES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gen" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".tzx" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sna" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".z80" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sg" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEG1K%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sms" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEGMS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gg" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEGG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".32x" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SG32X%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pbp" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sgx" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SGFX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sad" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mgt" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sdf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sbt" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".td0" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".cbm" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pce" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%TG16%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".d77" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".t77" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vfd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dim" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%X68K%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gcm" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NGC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vec" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%VECTX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pgm" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAMs%\%CONS%\%EMARC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".fds" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NFAM%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sfc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SFAM%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nez" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".md" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".smd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngc" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".adf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%CAMIG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".rp2" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AMSTR%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dsk" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%GAM%\%CONS%\%AMSTR%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ccd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cdz" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cdi" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".iso" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".img" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".nrg" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".mdf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".mds" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cue" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".bin" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".adf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".rom" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".do" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".po" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2mg" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cas" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".xdf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ipf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dsk" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".tap" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".wav" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".hdf" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dup" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".d88" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2hd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2dd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".fdi" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dsd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ssd" "%SEVENZIP%" e -y "%ZIPN%" -o"%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if "%FNDEXT%"=="1" move /Y "%ZIPN%" "%GBG%\%ROMJ%\SORTED ARCHIVES"