pushd "%GBC%"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.begin.set"') do echo.%%~a>"%GBC%\mkfav.vbs"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [FAV] "%GBG%\%ROMJ%"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [NAM] "~RoM-Jacket~"
if not exist "%GBG%\%ROMJ%" "%GBG%\%ROMJ%"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.set"') do echo.%%~a>>"%GBC%\mkfav.vbs"
cscript //B "mkfav.vbs"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.begin.set"') do echo.%%~a>"%GBC%\mkfav.vbs"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [FAV] "%GBG%\%GAM%\%CONS%"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [NAM] "~Consoles~"
if not exist "%GBG%\%GAM%\%CONS%" "%GBG%\%GAM%\%CONS%"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.set"') do echo.%%~a>>"%GBC%\mkfav.vbs"
cscript //B "mkfav.vbs"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.begin.set"') do echo.%%~a>"%GBC%\mkfav.vbs"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [FAV] "%GBE%\%EMUZ%"
"%GBC%\fart.exe" "%GBC%\mkfav.vbs" [NAM] "~Emulators~"
if not exist "%GBE%\%EMUZ%" mkdir "%GBE%\%EMUZ%"
for /f "tokens=* delims= " %%a in ('type "%GBC%\mkfav.set"') do echo.%%~a>>"%GBC%\mkfav.vbs"
cscript //B "mkfav.vbs"