if "%CVAREMU%"=="Atari800" set SHRTE=A800
if "%CVAREMU%"=="Akiko" set SHRTE=AKIKO
if "%CVAREMU%"=="Altirra" set SHRTE=ALTRA
if "%CVAREMU%"=="ArcEm" set SHRTE=ARCEM
if "%CVAREMU%"=="Arculator" set SHRTE=ARLTR
if "%CVAREMU%"=="Anex86" set SHRTE=ANEX
if "%CVAREMU%"=="ArcadePCLoader" set SHRTE=APCL
if "%CVAREMU%"=="AppleWin" set SHRTE=APLWIN
if "%CVAREMU%"=="atari++" set SHRTE=ATRI
if "%CVAREMU%"=="BatchScriptLauncher" set SHRTE=BATCHL
if "%CVAREMU%"=="BeebEm" set SHRTE=BEEBEM
if "%CVAREMU%"=="bsnes" set SHRTE=BSNS
if "%CVAREMU%"=="BlueMSX" set SHRTE=BMSX
if "%CVAREMU%"=="cps3emulator" set SHRTE=CPS3EMU
if "%CVAREMU%"=="Colem" set SHRTE=COLEM
if "%CVAREMU%"=="Demul" set SHRTE=DMUL
if "%CVAREMU%"=="DesMume" set SHRTE=DESMUME
if "%CVAREMU%"=="Dolphin" set SHRTE=DOLPH
if "%CVAREMU%"=="ElectrEm" set SHRTE=ELECEM
if "%CVAREMU%"=="em7" set SHRTE=EMSEV
if "%CVAREMU%"=="ePSXe" set SHRTE=EPSXE
if "%CVAREMU%"=="FinalBurnAlpha" set SHRTE=FBA
if "%CVAREMU%"=="Unz" set SHRTE=FMUNZ
if "%CVAREMU%"=="4DO" set SHRTE=FOURDO
if "%CVAREMU%"=="FlashPlayer" set SHRTE=FSHPL
if "%CVAREMU%"=="FreeDO" set SHRTE=FRDO
if "%CVAREMU%"=="FS-UAE" set SHRTE=FSUAE
if "%CVAREMU%"=="Fusion" set SHRTE=FUSN
if "%CVAREMU%"=="fceux" set SHRTE=FCEUX
if "%CVAREMU%"=="hatari" set SHRTE=HATARI
if "%CVAREMU%"=="Bliss" set SHRTE=INTV
if "%CVAREMU%"=="jum52" set SHRTE=JUM52
if "%CVAREMU%"=="Jagulator" set SHRTE=JAGLT
if "%CVAREMU%"=="jnes" set SHRTE=JNES
if "%CVAREMU%"=="jpcsp" set SHRTE=JPCSP
if "%CVAREMU%"=="jzintv" set SHRTE=JZINTV
if "%CVAREMU%"=="Kegs32" set SHRTE=KEGS
if "%CVAREMU%"=="M88" set SHRTE=M88
if "%CVAREMU%"=="m2emulator" set SHRTE=M2EMU
if "%CVAREMU%"=="Mednafen" set SHRTE=MEDN
if "%CVAREMU%"=="MagicEngine" set SHRTE=MENG
if "%CVAREMU%"=="Mame" set SHRTE=MAME
if "%CVAREMU%"=="Mess" set SHRTE=MESS
if "%CVAREMU%"=="DOSBox" set SHRTE=MSBOX
if "%CVAREMU%"=="Mugen" set SHRTE=MUGN
if "%CVAREMU%"=="Nebula" set SHRTE=NEBULA
if "%CVAREMU%"=="Neko" set SHRTE=NEKO
if "%CVAREMU%"=="neocd" set SHRTE=NEOCDEMU
if "%CVAREMU%"=="NeoRaine" set SHRTE=NEORAINE
if "%CVAREMU%"=="nestopia" set SHRTE=NESTP
if "%CVAREMU%"=="No$GBA" set SHRTE=NOGBA
if "%CVAREMU%"=="Nostalgia" set SHRTE=NOSTL
if "%CVAREMU%"=="NullDC" set SHRTE=NULLDC
if "%CVAREMU%"=="Ootake" set SHRTE=OOTK
if "%CVAREMU%"=="OpenMSX" set SHRTE=OPNMSX
if "%CVAREMU%"=="Pcsx2" set SHRTE=PCSX2
if "%CVAREMU%"=="PopCap" set SHRTE=PCAP
if "%CVAREMU%"=="Project64" set SHRTE=PJ64
if "%CVAREMU%"=="ParaJVE" set SHRTE=PJVE
if "%CVAREMU%"=="3DOplay" set SHRTE=PLAY3DO
if "%CVAREMU%"=="ProSystem" set SHRTE=PROSYS
if "%CVAREMU%"=="PPSSPP" set SHRTE=PSSP
if "%CVAREMU%"=="psx" set SHRTE=PSX
if "%CVAREMU%"=="ProjectTempest" set SHRTE=PTMPS
if "%CVAREMU%"=="Raine" set SHRTE=RAINE
if "%CVAREMU%"=="ScummVM" set SHRTE=SCMVM
if "%CVAREMU%"=="SimCoupe" set SHRTE=SIMC
if "%CVAREMU%"=="snes9x" set SHRTE=SNES9X
if "%CVAREMU%"=="SNESGT" set SHRTE=SNESGT
if "%CVAREMU%"=="Supermodel" set SHRTE=SPRM3
if "%CVAREMU%"=="SSF" set SHRTE=SSF
if "%CVAREMU%"=="Steem" set SHRTE=STEEM
if "%CVAREMU%"=="Stella" set SHRTE=STLA
if "%CVAREMU%"=="FlashPlayer" set SHRTE=SWFPL
if "%CVAREMU%"=="TurboEngine" set SHRTE=TURBOE
if "%CVAREMU%"=="VirtualColeco" set SHRTE=VCOLEC
if "%CVAREMU%"=="VisualBoyAdvance" set SHRTE=VGBA
if "%CVAREMU%"=="WinVICE" set SHRTE=VICE
if "%CVAREMU%"=="VirtualJaguar" set SHRTE=VJAG
if "%CVAREMU%"=="VirtuaNes" set SHRTE=VNES
if "%CVAREMU%"=="EMU7800" set SHRTE=VSVH
if "%CVAREMU%"=="CD-I" set SHRTE=WCDI
if "%CVAREMU%"=="WinArcadia" set SHRTE=WINARC
if "%CVAREMU%"=="WinAPE" set SHRTE=WINAPE
if "%CVAREMU%"=="WinUAE" set SHRTE=WINUAE
if "%CVAREMU%"=="WinX68k" set SHRTE=WINX68K
if "%CVAREMU%"=="XM6" set SHRTE=XM6
if "%CVAREMU%"=="XM7" set SHRTE=XM7
if "%CVAREMU%"=="X1turbo" set SHRTE=XTURB
if "%CVAREMU%"=="Zinc" set SHRTE=ZINC
if "%CVAREMU%"=="Zsnes" set SHRTE=ZSNS
if "%CVAREMU%"=="ZXSPIN" set SHRTE=ZXSpin