if "%CSTCONS%"=="%ACBBC%" set SHRTN=ACBBC
if "%CSTCONS%"=="%ACARC%" set SHRTN=ACARC
if "%CSTCONS%"=="%ACELE%" set SHRTN=ACELE
if "%CSTCONS%"=="%AMSTR%" set SHRTN=AMSTR
if "%CSTCONS%"=="%APL2E%" set SHRTN=APL2E
if "%CSTCONS%"=="%AMSTR%" set SHRTN=APL2GS
if "%CSTCONS%"=="%ARCD%" set SHRTN=ARCD
if "%CSTCONS%"=="%EMARC%" set SHRTN=EMARC
if "%CSTCONS%"=="%AT26%" set SHRTN=AT26
if "%CSTCONS%"=="%AT52%" set SHRTN=AT52
if "%CSTCONS%"=="%AT78%" set SHRTN=AT78
if "%CSTCONS%"=="%JAG%" set SHRTN=JAG
if "%CSTCONS%"=="%JAGCD%" set SHRTN=JAGCD
if "%CSTCONS%"=="%LYNX%" set SHRTN=LYNX
if "%CSTCONS%"=="%ATST%" set SHRTN=ATST
if "%CSTCONS%"=="%AT8H%" set SHRTN=AT8H
if "%CSTCONS%"=="%ATMS%" set SHRTN=ATMS
if "%CSTCONS%"=="%BWS%" set SHRTN=BWS
if "%CSTCONS%"=="%BWSC%" set SHRTN=BWSC
if "%CSTCONS%"=="%COLEC%" set SHRTN=COLEC
if "%CSTCONS%"=="%CM64%" set SHRTN=CM64
if "%CSTCONS%"=="%CAMIG%" set SHRTN=CAMIG
if "%CSTCONS%"=="%AMIG32%" set SHRTN=AMIG32
if "%CSTCONS%"=="%CPS%" set SHRTN=CPS
if "%CSTCONS%"=="%CPS2%" set SHRTN=CPS2
if "%CSTCONS%"=="%CPS3%" set SHRTN=CPS3
if "%CSTCONS%"=="%FLASH%" set SHRTN=FLASH
if "%CSTCONS%"=="%FM7%" set SHRTN=FM7
if "%CSTCONS%"=="%FMTOWNS%" set SHRTN=FMTOWNS
if "%CSTCONS%"=="%NEO64%" set SHRTN=NEO64
if "%CSTCONS%"=="%INTEL%" set SHRTN=INTEL
if "%CSTCONS%"=="%MSX%" set SHRTN=MSX
if "%CSTCONS%"=="%NAOMI%" set SHRTN=NAOMI
if "%CSTCONS%"=="%NEOCD%" set SHRTN=NEOCD
if "%CSTCONS%"=="%NEOGE%" set SHRTN=NEOGE
if "%CSTCONS%"=="%NEOPKT%" set SHRTN=NEOPKT
if "%CSTCONS%"=="%NEOPKTC%" set SHRTN=NEOPKTC
if "%CSTCONS%"=="%N64%" set SHRTN=N64
if "%CSTCONS%"=="%NDS%" set SHRTN=NDS
if "%CSTCONS%"=="%NES%" set SHRTN=NES
if "%CSTCONS%"=="%NFAM%" set SHRTN=NFAM
if "%CSTCONS%"=="%NGB%" set SHRTN=NGB
if "%CSTCONS%"=="%NGBC%" set SHRTN=NGBC
if "%CSTCONS%"=="%NGBA%" set SHRTN=NGBA
if "%CSTCONS%"=="%NGC%" set SHRTN=NGC
if "%CSTCONS%"=="%NVB%" set SHRTN=NVB
if "%CSTCONS%"=="%WII%" set SHRTN=WII
if "%CSTCONS%"=="%P3DO%" set SHRTN=P3DO
if "%CSTCONS%"=="%PCFX%" set SHRTN=PCFX
if "%CSTCONS%"=="%PC88%" set SHRTN=PC88
if "%CSTCONS%"=="%PC98%" set SHRTN=PC98
if "%CSTCONS%"=="%CDI%" set SHRTN=CDI
if "%CSTCONS%"=="%SAMC%" set SHRTN=SAMC
if "%CSTCONS%"=="%SG32X%" set SHRTN=SG32X
if "%CSTCONS%"=="%SEGCD%" set SHRTN=SEGCD
if "%CSTCONS%"=="%SEGDC%" set SHRTN=SEGDC
if "%CSTCONS%"=="%SEGG%" set SHRTN=SEGG
if "%CSTCONS%"=="%SEGAG%" set SHRTN=SEGAG
if "%CSTCONS%"=="%SEGAMD%" set SHRTN=SEGAMD
if "%CSTCONS%"=="%SEGMS%" set SHRTN=SEGMS
if "%CSTCONS%"=="%SEGM2%" set SHRTN=SEGM2
if "%CSTCONS%"=="%SEGM3%" set SHRTN=SEGM3
if "%CSTCONS%"=="%SSAT%" set SHRTN=SSAT
if "%CSTCONS%"=="%SEG1K%" set SHRTN=SEG1K
if "%CSTCONS%"=="%ZXSP%" set SHRTN=ZXSP
if "%CSTCONS%"=="%PS1%" set SHRTN=PS1
if "%CSTCONS%"=="%PSP%" set SHRTN=PSP
if "%CSTCONS%"=="%PS2%" set SHRTN=PS2
if "%CSTCONS%"=="%SFAM%" set SHRTN=SFAM
if "%CSTCONS%"=="%SNES%" set SHRTN=SNES
if "%CSTCONS%"=="%TAITX%" set SHRTN=TAITX
if "%CSTCONS%"=="%TOUHU%" set SHRTN=TOUHU
if "%CSTCONS%"=="%PCENG%" set SHRTN=PCENG
if "%CSTCONS%"=="%PCECD%" set SHRTN=PCECD
if "%CSTCONS%"=="%SGFX%" set SHRTN=SGFX
if "%CSTCONS%"=="%TG16%" set SHRTN=TG16
if "%CSTCONS%"=="%TGCD%" set SHRTN=TGCD
if "%CSTCONS%"=="%VECTX%" set SHRTN=VECTX
if "%CSTCONS%"=="%WIN32%" set SHRTN=WIN32
if "%CSTCONS%"=="%X68K%" set SHRTN=X68K
if "%CSTCONS%"=="%SHRPX1%" set SHRTN=SHRPX1